### ISSUE TITLE
Node 14 Tracking Issue

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#288]
At some point we're going to want to move to Node 14, so I'm creating this issue to track known dependency open issues and changes that we might have to make when we do the upgrade. We don't really use Node internals much so I'm not expecting many code-level changes, just dep updates and build process / configuration tweaks.

- [ ] Chokidar 2 will break on Node 14, which is a dependency of the NextJS Webpack 4 build. They have an open issue to upgrade to Webpack 5, but it looks like it might be non-trivial on their end.

- [x] [ts-node-dev support does not seem to be working yet](https://github.com/whitecolor/ts-node-dev/issues/143). A potential workaround would be to switch (back) to nodemon or similar if they don't catch up in a reasonable amount of time.

- [ ] ES modules should be fully supported, so we can switch our tsconfig.jsons to use that, as well as the latest appropriate compilation targets and libraries.

Please feel free to add to this issue as you come across other blockers or todos.

**Comment by bk3c** [comment]
We're now upgraded to NextJS 9.5 (see #456) which includes beta Webpack 5 support, so Node 14 should be realistic in a few weeks when Webpack 5 is GA and things have settled down.
