### ISSUE TITLE
[Meta] October 2020 Object Model Changes

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#747]
This is meant as a meta-issue to track a host of object model changes that we'd like to get done this month, each of which should (eventually) be defined in their own issues, but I thought would be worth consolidating here so that we could manage it as a unified process since it's a **huge** amount of interrelated plumbing work to get done. 

Some other issues we do concurrently might also have minor object model implications (e.g. adding a field) that won't be tracked here, but this is meant to track the object model overhaul that will put us in good shape for the next several months of feature development.

- [x] Move to integer as DB primary keys and Hashids as public object IDs, instead of UUIDs (#348)
- [x] Split out Properties from Listings (#317) - PR 
- [x] Rationalize fields between Properties, Units, and Listings (#317)
- [x] Add PropertyGroups, which are mostly a container for permission assignment across multiple properties (#317)
- [x] Move AMI charts into the database (with a more general name) (#328) - PR
- [x] Split out* Applicants from Applications (#843) - PR
- [x] Add backend object for Application Form Config (1:1 with listings?) and rationalize with Listings as appropriate (#855) -PR
- [x] Migration of existing database 
- [x] Permissions based on property group 
- [ ] Add versioning of major objects (#286) 

-- 
- [ ] Build out object model for Preferences and Eligibility Rules that can be edited and machine-evaluated

Since this is such a substantial overhaul of the schema, I think it's acceptable to plan to rebuild production databases from scratch, so long as we can re-create the listings and have some manual process for the one-time export and re-import the Applications from the Jones pilot, which will certainly be over by the time we land this in production.

**Comment by pbn4** [comment]
One thing to remember with ApplicationFormConfig is to create an entry for all the records once we get rid of the frontend embedded application form config. I marked it as a TODO in frontend code.

**Comment by pbn4** [comment]
@jaredcwhite @software-project @netrabadami @dominikx96 For permissions management we are now using Casbin which defines a CSV backend side with all the rules for evaluation whether a specific user can or cannot call given action / access given resource. It looks like this:

```
p, admin, application, true, .*
p, anonymous, application, true, submit
p, anonymous, user, true, create
g, admin, user
g, user, anonymous
```

and is embedded in the code. It's quite nice because at controller level you only define what it the resource type and what is the action and based on a request Casbin evalutes whether given user is authorized to perform given action on a given resource or not. Unfortunately I haven't found a solution for casbin to easily share permissions between frontend and backend. 

So currently we have this problem of user e.g. a developer going into partners portal and seeing all this stuff, trying to manipulate something e.g. an application and sees a "403 Forbidden" response because only the backend knows that he is not authorized to perform Update on an Application. 

**If we want to improve UX** we need to somehow share action:subject permissions with the frontend to be able to not display applications at all for a user with no permissions. Below propositions only address permissions sharing between frontend and API problem (they do not address permissions model). 

1. Replace Casbin with CASL 
[CASL](https://github.com/stalniy/casl) comes with a declarative style rules (same as Casbin) but also provides frontend libraries to work with them [@casl/react](https://www.npmjs.com/package/@casl/react). One can easily serialize rules on the backend and send them along with e.g. access token to dynamically build site navigation. Example rules:

   ```
   [
     {"action":"manage", "subject":"all"},
     {"action":"manage", "subject":"Application", "conditions":{"listingId":5}}
   ]
   ```

   This can later be consumed using Abilities in a way you @software-project @jaredcwhite are used to:

   ```
   export default () => <Can not I="create" a="Post">
      You are not allowed to create a post
   </Can>
   ```
  
   This solution I came up with after reading https://medium.com/dailyjs/casl-and-cancan-permissions-sharing-between-ui-and-api-5f1fa8b4bec

2. Stay with Casbin and throw a 403 each time user tries to do something he has no permissionsfor  e.g. entering applications table would yield an empty table maybe with some warning/error indicator in place of data. That would also mean for a user with read permissions a forbidden response in a case where he tries to edit the data: he can fill out e.g. entire paper application and only submit to know that he can't actually do that.

**Comment by kathyccheng** [comment]
Epic looks good
